# Generated by Django 3.0.8 on 2020-08-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_closed_auctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_auctions',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auctions'),
        ),
    ]
